steps:
  - name: 'python:3.11'
    id: 'Install dependencies and run Python tests'
    dir: 'gcp-python-ci-cd-demo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pytest
        
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Python container image'
    dir: 'gcp-python-ci-cd-demo'
    args:
      - 'build'
      - '-t'
      - 'australia-southeast2-docker.pkg.dev/gcp-cicd-assignment-python/gcp-python-ci-cd-demo/gcp-python-ci-cd-demo:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Python container image'
    args:
      - 'push'
      - 'australia-southeast2-docker.pkg.dev/gcp-cicd-assignment-python/gcp-python-ci-cd-demo/gcp-python-ci-cd-demo:$SHORT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Python application to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gcp-python-ci-cd-demo'
      - '--image'
      - 'australia-southeast2-docker.pkg.dev/gcp-cicd-assignment-python/gcp-python-ci-cd-demo/gcp-python-ci-cd-demo:$SHORT_SHA'
      - '--region'
      - 'australia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'australia-southeast2-docker.pkg.dev/gcp-cicd-assignment-python/gcp-python-ci-cd-demo/gcp-python-ci-cd-demo:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY